development:
  username: cedenoh
  password: Y123456.
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


test:
  username: cedenoh
  password: Y123456.
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  username: cedenoh
  password: Y123456.
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
